#!/usr/bin/env python3
"""
NemoClaw Skill — Video Composer v1.0.0 (cnt-12-video-composer)
Composes short-form videos from script text. Generates image prompts, calls video composer tool,
and runs quality checks via critic loop.
Generated by NemoClaw E-9. LangGraph v4.0 + SqliteSaver.
"""
import argparse, json, os, sys, time, sqlite3, subprocess
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SKILL_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = SKILL_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root for lib.routing

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from typing import TypedDict

CHECKPOINT_DB = Path.home() / ".nemoclaw" / "checkpoints" / "langgraph.db"
CHECKPOINT_DB.parent.mkdir(parents=True, exist_ok=True)

SKILL_ID = "cnt-12-video-composer"


class SkillState(TypedDict):
    inputs: dict; context: dict; step_1_output: str; step_2_output: str
    step_3_output: str; generated_output: str; quality_score: float
    critic_feedback: str; retry_count: int; final_output: str
    artifact_path: str; envelope_path: str; error: str; cost: float


def call_llm(messages, max_tokens=4000):
    from lib.routing import call_llm as _routed_call
    return _routed_call(messages, task_class="moderate", max_tokens=max_tokens)

def estimate_cost(task_class="moderate"):
    from lib.routing import estimate_cost as _est
    return _est(task_class)

def load_spec(args):
    spec = {"inputs": {}, "context": {"workflow_id": args.thread_id or f"skill-{SKILL_ID}-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}-{os.urandom(4).hex()}", "budget_state": {"remaining": 20.0}, "step_history": []}}
    if args.input:
        for pair in args.input: spec["inputs"][pair[0]] = pair[1]
    if args.input_from:
        ep = Path(args.input_from)
        if ep.exists(): spec["inputs"].update(json.loads(ep.read_text()).get("outputs", {}))
    return spec

def validate_inputs(spec):
    errors = []
    for key in list(spec.get("inputs", {}).keys()):
        val = spec["inputs"][key]
        if not isinstance(val, str): spec["inputs"][key] = str(val)
        spec["inputs"][key] = spec["inputs"][key].replace("\x00", "").strip()
        if len(spec["inputs"][key]) > 50000: spec["inputs"][key] = spec["inputs"][key][:50000]
    if not spec["inputs"].get("script_text") or len(spec["inputs"]["script_text"]) < 20:
        errors.append("Missing required input: script_text (min 20 chars)")
    if not spec["inputs"].get("agent_id"):
        errors.append("Missing required input: agent_id")
    if not spec["inputs"].get("platform"):
        spec["inputs"]["platform"] = "tiktok"
    if errors:
        for e in errors: print(f"  ERROR: {e}")
        sys.exit(1)

# Step 1: Parse Script (local)
def step_1_parse(state):
    script = spec["inputs"].get("script_text", "")
    agent_id = spec["inputs"].get("agent_id", "")
    platform = spec["inputs"].get("platform", "tiktok")
    visual_style = spec["inputs"].get("visual_style", "slideshow")
    context = f"Script: {script}\nAgent: {agent_id}\nPlatform: {platform}\nStyle: {visual_style}"
    return {**state, "step_1_output": context}

# Step 2: Generate Visuals (llm - creates image prompts from script)
def step_2_generate_visuals(state):
    context = state["step_1_output"]
    feedback = state.get("critic_feedback", "")
    fb = f"\n\nPrevious feedback (improve):\n{feedback}" if feedback else ""
    messages = [("system", "You are a visual director for short-form video. Given a script, output a JSON array of scene objects with keys: scene_number, description, image_prompt, duration_seconds, text_overlay."), ("human", f"{context}{fb}")]
    cost = estimate_cost()
    content, error = call_llm(messages)
    if error or not content: return {**state, "error": str(error or "Empty response")}
    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "step_2_output": content, "cost": state.get("cost", 0) + cost}

# Step 3: Compose Video (local - calls tools/video-composer/compose.py)
def step_3_compose(state):
    visuals = state.get("step_2_output", "")
    platform = spec["inputs"].get("platform", "tiktok")
    agent_id = spec["inputs"].get("agent_id", "")
    visual_style = spec["inputs"].get("visual_style", "slideshow")
    composer_script = Path(__file__).resolve().parents[2] / "tools" / "video-composer" / "compose.py"
    result_lines = [f"## Video Composition Report\n", f"- Platform: {platform}", f"- Agent: {agent_id}", f"- Style: {visual_style}", f"- Scenes: {visuals[:500]}"]
    if composer_script.exists():
        try:
            proc = subprocess.run([sys.executable, str(composer_script), "--platform", platform, "--style", visual_style], capture_output=True, text=True, timeout=120)
            result_lines.append(f"\n### Composer Output\n{proc.stdout[:1000]}")
        except Exception as e:
            result_lines.append(f"\n### Composer Note\nVideo composer not available: {e}")
    else:
        result_lines.append(f"\n### Composer Note\nVideo composer tool not found at {composer_script}. Scenes planned for offline composition.")
    output = "\n".join(result_lines)
    return {**state, "step_3_output": output, "generated_output": output}

# Step 4: Quality Check (critic)
def step_4_critic(state):
    output = state.get("generated_output", "")
    if not output or len(output) < 30: return {**state, "quality_score": 0.0, "critic_feedback": "Too short"}
    score = 5.0
    if "Scene" in output or "scene" in output: score += 1.0
    if "image_prompt" in output: score += 1.0
    if len(output) > 300: score += 0.5
    if "Platform" in output: score += 0.5
    feedback = ""
    if score < 9.5:
        try:
            from langchain_anthropic import ChatAnthropic
            from lib.routing import resolve_alias as _ra
            _cp, _cm, _cc = _ra("structured_short")
            resp = ChatAnthropic(model=_cm, max_tokens=300).invoke([("system", 'Score 1-10 as JSON: {"score":N,"feedback":"..."}'), ("human", f"Task: Video Composer\n\nOutput:\n{output[:2000]}")])
            text = resp.content.strip()
            if "{" in text:
                data = json.loads(text[text.index("{"):text.rindex("}") + 1])
                llm_score = data.get("score", 5); feedback = data.get("feedback", "")
                score = llm_score  # LLM critic score replaces heuristic
                state = {**state, "cost": state.get("cost", 0) + 0.008}
        except Exception as _e:
            import logging; logging.getLogger("nemoclaw.critic").warning(f"Critic call failed: {_e}")
    return {**state, "quality_score": min(score, 10.0), "critic_feedback": feedback, "final_output": output}

def should_retry(state):
    if state.get("quality_score", 0) < 9.0 and state.get("retry_count", 0) < 4: return "retry"
    return "accept"

def step_retry(state): return {**state, "retry_count": state.get("retry_count", 0) + 1}

def step_artifact(state):
    output = state.get("final_output", state.get("generated_output", ""))
    wf_id = state["context"]["workflow_id"]
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    md_path = OUTPUTS_DIR / f"{SKILL_ID}_{wf_id}_{ts}.md"
    md_path.write_text(output)
    env_path = OUTPUTS_DIR / f"{SKILL_ID}_{wf_id}_{ts}_envelope.json"
    envelope = {"skill_id": SKILL_ID, "workflow_id": wf_id, "timestamp": datetime.now(timezone.utc).isoformat(),
        "outputs": {"result": output, "result_summary": output[:300], "skill_type": "executor",
            "metadata": {"quality_score": state.get("quality_score", 0), "retries": state.get("retry_count", 0), "cost": state.get("cost", 0)}},
        "artifact_path": str(md_path), "quality_score": state.get("quality_score", 0), "cost": state.get("cost", 0)}
    env_path.write_text(json.dumps(envelope, indent=2, default=str))
    return {**state, "artifact_path": str(md_path), "envelope_path": str(env_path)}

def build_graph():
    g = StateGraph(SkillState)
    g.add_node("step_1", step_1_parse); g.add_node("step_2", step_2_generate_visuals)
    g.add_node("step_3", step_3_compose); g.add_node("step_4", step_4_critic)
    g.add_node("step_retry", step_retry); g.add_node("step_artifact", step_artifact)
    g.set_entry_point("step_1"); g.add_edge("step_1", "step_2"); g.add_edge("step_2", "step_3")
    g.add_edge("step_3", "step_4")
    g.add_conditional_edges("step_4", should_retry, {"retry": "step_retry", "accept": "step_artifact"})
    g.add_edge("step_retry", "step_2"); g.add_edge("step_artifact", END)
    return g

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", default=SKILL_ID); parser.add_argument("--input", nargs=2, action="append")
    parser.add_argument("--thread-id", default=None); parser.add_argument("--resume", action="store_true")
    parser.add_argument("--input-from", default=None); parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    spec = load_spec(args); validate_inputs(spec)
    wf_id = spec["context"]["workflow_id"]
    if not args.force:
        existing = list(OUTPUTS_DIR.glob(f"{SKILL_ID}_*_envelope.json"))
        if existing: print(f"Skip: Output exists ({sorted(existing)[-1].name}). Use --force."); sys.exit(0)
    print(f"\nStarting: Video Composer v1.0.0\nThread: {wf_id}")
    graph = build_graph(); conn = sqlite3.connect(str(CHECKPOINT_DB), check_same_thread=False); ckpt = SqliteSaver(conn)
    app = graph.compile(checkpointer=ckpt)
    init = {"inputs": spec["inputs"], "context": spec["context"], "step_1_output": "", "step_2_output": "",
        "step_3_output": "", "generated_output": "", "quality_score": 0.0, "critic_feedback": "",
        "retry_count": 0, "final_output": "", "artifact_path": "", "envelope_path": "", "error": "", "cost": 0.0}
    config = {"configurable": {"thread_id": wf_id}}
    for step in app.stream(init, config):
        for nn, ns in step.items():
            if ns.get("error"): print(f"  [error] {ns['error']}"); break
    final = app.get_state(config)
    if final and final.values:
        v = final.values
        if v.get("artifact_path"): print(f"\nComplete: Video Composer\nOutput: {v['artifact_path']}\nQuality: {v.get('quality_score',0):.1f}/10\nCost: ${v.get('cost',0):.3f}")
        elif v.get("error"): print(f"\nFAILED: {v['error']}")
    conn.close()
