#!/usr/bin/env python3
"""
NemoClaw Skill — SEO Technical Auditor v1.0.0 (k56-seo-technical-auditor)

Technical SEO audit — site structure, page speed, meta tags, schema markup recommendations.

Generated by NemoClaw Skill Factory (E-5/E-6).
Runner: LangGraph v4.0 + SqliteSaver
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# -- Paths -----------------------------------------------------------------

REPO = Path(__file__).resolve().parents[1]
SKILL_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = SKILL_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root for lib.routing

# -- LangGraph -------------------------------------------------------------

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from typing import TypedDict
import sqlite3

CHECKPOINT_DB = Path.home() / ".nemoclaw" / "checkpoints" / "langgraph.db"
CHECKPOINT_DB.parent.mkdir(parents=True, exist_ok=True)

SKILL_ID = "k56-seo-technical-auditor"


class SkillState(TypedDict):
    inputs: dict
    context: dict
    step_1_output: str
    generated_output: str
    quality_score: float
    critic_feedback: str
    retry_count: int
    final_output: str
    artifact_path: str
    envelope_path: str
    error: str
    cost: float

# -- LLM Helpers -----------------------------------------------------------


def call_llm(messages, max_tokens=4000):
    from lib.routing import call_llm as _routed_call
    return _routed_call(messages, task_class="moderate", max_tokens=max_tokens)


def call_cheap_critic(output_text, task_description):
    messages = [
        ("system", "You are a strict quality evaluator. Score 1-10: 9-10=excellent (comprehensive, well-structured, actionable, professional-grade), 7-8=good (solid but missing depth), 5-6=acceptable, 1-4=poor. Be generous with detailed, well-structured outputs. Return ONLY JSON: {\"score\": N, \"feedback\": \"...\"}"),
        ("human", f"Task: {task_description}\n\nOutput to evaluate:\n{output_text[:2000]}"),
    ]
    try:
        from lib.routing import call_llm
        _critic_text, _critic_err = call_llm(messages, "structured_short", 300)
        text = _critic_text.strip() if _critic_text else ""
        if "{" in text:
            json_str = text[text.index("{"):text.rindex("}") + 1]
            data = json.loads(json_str)
            return data.get("score", 5), data.get("feedback", "")
    except Exception:
        pass
    return 5.0, "Critic unavailable"


def estimate_cost(task_class="moderate"):
    from lib.routing import estimate_cost as _est
    return _est(task_class)


# -- Skill Spec ------------------------------------------------------------


def load_spec(args):
    spec = {
        "inputs": {},
        "context": {
            "workflow_id": args.thread_id or f"skill-{SKILL_ID}-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}-{os.urandom(4).hex()}",
            "budget_state": {"remaining": 20.0},
            "step_history": [],
        },
    }
    if args.input:
        for pair in args.input:
            spec["inputs"][pair[0]] = pair[1]
    if args.input_from:
        envelope_path = Path(args.input_from)
        if envelope_path.exists():
            envelope = json.loads(envelope_path.read_text())
            spec["inputs"].update(envelope.get("outputs", {}))
    return spec


def validate_inputs(spec):
    errors = []
    if not spec["inputs"].get("website_url") or len(spec["inputs"]["website_url"]) < 10:
        errors.append("Missing required input: website_url (min 10 chars)")
    if errors:
        print("ERROR: Input validation failed:")
        for e in errors:
            print(f"  {e}")
        sys.exit(1)


# -- Steps -----------------------------------------------------------------


def step_1_parse(state):
    website_url = spec["inputs"].get("website_url", "")
    focus_areas = spec["inputs"].get("focus_areas", "all")
    depth = spec["inputs"].get("depth", "standard")

    context = f"""Task: Technical SEO Audit
- website_url: {website_url}
- focus_areas: {focus_areas}
- depth: {depth}"""

    return {**state, "step_1_output": context}


def step_2_audit_structure(state):
    context = state["step_1_output"]
    feedback = state.get("critic_feedback", "")

    feedback_section = ""
    if feedback:
        feedback_section = f"\n\nPrevious attempt feedback (improve on this):\n{feedback}"

    messages = [
        ("system", "You are a technical SEO auditor specializing in site structure analysis, crawlability, and indexation."),
        ("human", f"""{context}{feedback_section}

Perform a technical SEO structure audit:
## URL Structure Analysis
(URL hierarchy, slug patterns, canonical tags, redirect chains)
## Internal Linking Audit
(Link depth, orphan pages, anchor text distribution, link equity flow)
## Crawlability Assessment
(Robots.txt review, XML sitemap analysis, crawl budget optimization)
## Indexation Issues
(Noindex tags, duplicate content, thin content pages, canonicalization)"""),
    ]

    from lib.routing import resolve_from_env_or_config as _resolve
    provider, model, _cost = _resolve("moderate")
    cost = estimate_cost()
    print(f"    [budget] alias=moderate model={model} cost=${cost} remaining=${state['context']['budget_state']['remaining']:.3f}")

    content, error = call_llm(messages)
    if error or not content:
        return {**state, "error": str(error or "Empty LLM response")}

    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": content, "cost": state.get("cost", 0) + cost}


def step_3_audit_performance(state):
    prev_output = state.get("generated_output", "")
    context = state["step_1_output"]

    messages = [
        ("system", "You are a technical SEO auditor specializing in page speed, Core Web Vitals, and on-page optimization."),
        ("human", f"""{context}

Previous structure audit:
{prev_output[:3000]}

Now audit performance and on-page elements:
## Page Speed Analysis
(Core Web Vitals: LCP, FID, CLS — optimization recommendations)
## Mobile Optimization
(Responsive design, mobile-first indexing, touch targets, viewport config)
## Meta Tags Audit
(Title tags, meta descriptions, Open Graph, Twitter Cards — best practices)
## Schema Markup Review
(Existing structured data, missing schema opportunities, JSON-LD recommendations)"""),
    ]

    cost = estimate_cost()
    content, error = call_llm(messages, max_tokens=4000)
    if error or not content:
        return {**state, "error": str(error or "Empty LLM response")}

    combined = prev_output + "\n\n---\n\n" + content
    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": combined, "cost": state.get("cost", 0) + cost}


def step_4_generate_recommendations(state):
    prev_output = state.get("generated_output", "")
    context = state["step_1_output"]

    messages = [
        ("system", "You are a technical SEO consultant who provides prioritized, actionable recommendations."),
        ("human", f"""{context}

Full audit findings:
{prev_output[:4000]}

Generate prioritized recommendations:
## Critical Issues (Fix Immediately)
(Issues blocking indexation or causing severe ranking penalties)
## High Priority (Fix Within 1 Week)
(Issues significantly impacting rankings or user experience)
## Medium Priority (Fix Within 1 Month)
(Optimization opportunities for meaningful improvement)
## Low Priority (Backlog)
(Nice-to-have improvements for marginal gains)
## Implementation Roadmap
(Step-by-step technical implementation guide for top 5 fixes)"""),
    ]

    cost = estimate_cost()
    content, error = call_llm(messages, max_tokens=4000)
    if error or not content:
        return {**state, "error": str(error or "Empty LLM response")}

    combined = prev_output + "\n\n---\n\n" + content
    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": combined, "cost": state.get("cost", 0) + cost}


def step_5_critic(state):
    output = state.get("generated_output", "")
    if not output or len(output) < 50:
        return {**state, "quality_score": 0.0, "critic_feedback": "Output too short"}

    score = 5.0
    if len(output) > 200: score += 0.5
    if len(output) > 500: score += 0.5
    if "##" in output: score += 0.5
    if "- " in output or "1." in output: score += 0.5
    if len(output) > 1000: score += 0.5
    score = min(score, 10.0)

    feedback = ""
    if score < 10.5:
        print(f"    [critic] Heuristic score {score:.1f} < 9.5 — running LLM critic")
        llm_score, feedback = call_cheap_critic(output, state.get("step_1_output", ""))
        cost = estimate_cost()
        state["context"]["budget_state"]["remaining"] -= cost
        score = llm_score
        state = {**state, "cost": state.get("cost", 0) + cost}
        print(f"    [critic] LLM score: {llm_score:.1f}, final: {score:.1f}")

    return {**state, "quality_score": score, "critic_feedback": feedback, "final_output": output}


def should_retry(state):
    score = state.get("quality_score", 0)
    retries = state.get("retry_count", 0)
    if score < 9.0 and retries < 4:
        print(f"    [retry] Score {score:.1f} < 9.0, retrying (attempt {retries + 1})")
        return "retry"
    return "accept"


def step_retry(state):
    return {**state, "retry_count": state.get("retry_count", 0) + 1}


def step_6_artifact(state):
    output = state.get("final_output", state.get("generated_output", ""))
    wf_id = state["context"]["workflow_id"]
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    md_name = f"{SKILL_ID}_{wf_id}_{ts}.md"
    md_path = OUTPUTS_DIR / md_name
    md_path.write_text(output)
    print(f"  [artifact] Written to: {md_path}")

    env_name = f"{SKILL_ID}_{wf_id}_{ts}_envelope.json"
    env_path = OUTPUTS_DIR / env_name

    key_points = []
    for line in output.split("\n"):
        line = line.strip()
        if line.startswith("- ") or line.startswith("1.") or line.startswith("* "):
            key_points.append(line.lstrip("- *0123456789.").strip())
        if len(key_points) >= 10:
            break

    envelope = {
        "skill_id": SKILL_ID,
        "workflow_id": wf_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "outputs": {
            "result": output,
            "result_summary": output[:300],
            "key_points": key_points,
            "skill_type": "analyzer",
            "metadata": {
                "quality_score": state.get("quality_score", 0),
                "retries": state.get("retry_count", 0),
                "cost": state.get("cost", 0),
                "model": __import__("lib.routing", fromlist=["resolve_from_env_or_config"]).resolve_from_env_or_config("moderate")[1],
            },
        },
        "artifact_path": str(md_path),
        "quality_score": state.get("quality_score", 0),
        "cost": state.get("cost", 0),
    }
    env_path.write_text(json.dumps(envelope, indent=2, default=str))
    print(f"  [envelope] Written to: {env_path}")

    return {**state, "artifact_path": str(md_path), "envelope_path": str(env_path)}


# -- Graph -----------------------------------------------------------------


def build_graph():
    graph = StateGraph(SkillState)
    graph.add_node("step_1", step_1_parse)
    graph.add_node("step_2", step_2_audit_structure)
    graph.add_node("step_3", step_3_audit_performance)
    graph.add_node("step_4", step_4_generate_recommendations)
    graph.add_node("step_5", step_5_critic)
    graph.add_node("step_retry", step_retry)
    graph.add_node("step_6", step_6_artifact)
    graph.set_entry_point("step_1")
    graph.add_edge("step_1", "step_2")
    graph.add_edge("step_2", "step_3")
    graph.add_edge("step_3", "step_4")
    graph.add_edge("step_4", "step_5")
    graph.add_conditional_edges("step_5", should_retry, {
        "retry": "step_retry",
        "accept": "step_6",
    })
    graph.add_edge("step_retry", "step_2")
    graph.add_edge("step_6", END)
    return graph


# -- Main ------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", default=SKILL_ID)
    parser.add_argument("--input", nargs=2, action="append", metavar=("KEY", "VALUE"))
    parser.add_argument("--thread-id", default=None)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--input-from", default=None)
    parser.add_argument("--force", action="store_true", help="Overwrite existing outputs")
    args = parser.parse_args()

    spec = load_spec(args)
    validate_inputs(spec)

    wf_id = spec["context"]["workflow_id"]

    if not args.force:
        existing = list(OUTPUTS_DIR.glob(f"{SKILL_ID}_*_envelope.json"))
        if existing:
            latest = sorted(existing)[-1]
            print(f"\nSkip: Output already exists ({latest.name})")
            print(f"Use --force to regenerate.")
            sys.exit(0)

    print(f"\nStarting skill: SEO Technical Auditor v1.0.0")
    print(f"Thread ID: {wf_id}")

    graph = build_graph()
    conn = sqlite3.connect(str(CHECKPOINT_DB), check_same_thread=False)
    checkpointer = SqliteSaver(conn)
    app = graph.compile(checkpointer=checkpointer)

    initial_state = {
        "inputs": spec["inputs"],
        "context": spec["context"],
        "step_1_output": "",
        "generated_output": "",
        "quality_score": 0.0,
        "critic_feedback": "",
        "retry_count": 0,
        "final_output": "",
        "artifact_path": "",
        "envelope_path": "",
        "error": "",
        "cost": 0.0,
    }

    config = {"configurable": {"thread_id": wf_id}}

    for step in app.stream(initial_state, config):
        for node_name, node_state in step.items():
            print(f"\n  [node] {node_name}")
            if node_state.get("error"):
                print(f"  [error] {node_state['error']}")
                break
            print(f"  [done] {node_name}")

    final = app.get_state(config)
    if final and final.values:
        vals = final.values
        if vals.get("artifact_path"):
            print(f"\nSkill complete: SEO Technical Auditor")
            print(f"Thread ID: {wf_id}")
            print(f"Output: {vals['artifact_path']}")
            print(f"Quality: {vals.get('quality_score', 0):.1f}/10")
            print(f"Cost: ${vals.get('cost', 0):.3f}")
        elif vals.get("error"):
            print(f"\nERROR: Skill failed — {vals['error']}")

    conn.close()
