#!/usr/bin/env python3
"""
NemoClaw Skill — Ad Campaign Builder v1.0.0 (k41-ad-campaign-builder)

Generates complete ad campaign plans with targeting, creative briefs, budget allocation, and A/B test variants.

Generated by NemoClaw Skill Factory (E-5/E-6).
Runner: LangGraph v4.0 + SqliteSaver
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────

REPO = Path(__file__).resolve().parents[1]
SKILL_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = SKILL_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root for lib.routing

# ── LangGraph ──────────────────────────────────────────────────────────

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from typing import TypedDict
import sqlite3

CHECKPOINT_DB = Path.home() / ".nemoclaw" / "checkpoints" / "langgraph.db"
CHECKPOINT_DB.parent.mkdir(parents=True, exist_ok=True)


class SkillState(TypedDict):
    inputs: dict
    context: dict
    step_1_output: str
    generated_output: str
    quality_score: float
    critic_feedback: str
    retry_count: int
    final_output: str
    artifact_path: str
    envelope_path: str
    error: str
    cost: float

# ── LLM Helpers ────────────────────────────────────────────────────────


def call_llm(messages, max_tokens=4000):
    from lib.routing import call_llm as _routed_call
    return _routed_call(messages, task_class="moderate", max_tokens=max_tokens)

def call_anthropic(messages, model=None, max_tokens=4000):
    if model is None:
        from lib.routing import resolve_alias
        _, model, _ = resolve_alias("complex_reasoning")
    from langchain_anthropic import ChatAnthropic
    llm = ChatAnthropic(model=model, max_tokens=max_tokens)
    resp = llm.invoke(messages)
    return resp.content, None


def call_openai(messages, model=None, max_tokens=4000):
    if model is None:
        from lib.routing import resolve_alias
        _, model, _ = resolve_alias("general_short")
    from langchain_openai import ChatOpenAI
    llm = ChatOpenAI(model=model, max_tokens=max_tokens)
    resp = llm.invoke(messages)
    return resp.content, None


def call_cheap_critic(output_text, task_description):
    """LLM-based critic using cheapest model (Fix #1)."""
    messages = [
        ("system", "You are a quality evaluator. Score the output 1-10 on: task completion, correctness, usefulness, structure. Return ONLY a JSON object: {\"score\": N, \"feedback\": \"...\"}"),
        ("human", f"Task: {task_description}\n\nOutput to evaluate:\n{output_text[:2000]}"),
    ]
    try:
        from langchain_anthropic import ChatAnthropic
        from lib.routing import resolve_alias as _ra
        _cp, _cm, _cc = _ra("structured_short")
        llm = ChatAnthropic(model=_cm, max_tokens=300)
        resp = llm.invoke(messages)
        # Parse JSON from response
        text = resp.content.strip()
        if "{" in text:
            json_str = text[text.index("{"):text.rindex("}")+2]
            data = json.loads(json_str)
            return data.get("score", 5), data.get("feedback", "")
    except Exception:
        pass
    return 5.0, "Critic unavailable"


def estimate_cost(task_class="moderate"):
    from lib.routing import estimate_cost as _est
    return _est(task_class)


# ── Skill Spec ─────────────────────────────────────────────────────────

def load_spec(args):
    spec = {
        "inputs": {},
        "context": {
            "workflow_id": args.thread_id or f"skill-k41-ad-campaign-builder-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}-{os.urandom(4).hex()}",
            "budget_state": {"remaining": 20.0},
            "step_history": [],
        },
    }
    if args.input:
        for pair in args.input:
            spec["inputs"][pair[0]] = pair[1]
    if args.input_from:
        envelope_path = Path(args.input_from)
        if envelope_path.exists():
            envelope = json.loads(envelope_path.read_text())
            spec["inputs"].update(envelope.get("outputs", {}))
    return spec


def validate_inputs(spec):
    errors = []
    if not spec["inputs"].get("campaign_goal") or len(spec["inputs"]["campaign_goal"]) < 10:
        errors.append("Missing required input: campaign_goal")
    if not spec["inputs"].get("budget") or len(spec["inputs"]["budget"]) < 5:
        errors.append("Missing required input: budget")
    if errors:
        print("ERROR: Input validation failed:")
        for e in errors:
            print(f"  {e}")
        sys.exit(1)


# ── Steps ──────────────────────────────────────────────────────────────

def step_1_parse(state):
    campaign_goal = spec["inputs"].get("campaign_goal", "")
    budget = spec["inputs"].get("budget", "")
    platform = spec["inputs"].get("platform", "google_ads")
    
    context = f"""Task: Ad Campaign Builder
- campaign_goal: {campaign_goal}
- budget: {budget}
- platform: {platform}"""
    
    return {**state, "step_1_output": context}


def step_2_generate(state):
    context = state["step_1_output"]
    feedback = state.get("critic_feedback", "")
    
    feedback_section = ""
    if feedback:
        feedback_section = f"\n\nPrevious attempt feedback (improve on this):\n{feedback}"
    
    messages = [
        ("system", """You are a digital advertising strategist. Create comprehensive ad campaign plans with targeting and creative."""),
        ("human", f"""{context}{feedback_section}

Produce polished, ready-to-use output with these sections:
## Overview
(Brief context and purpose)
## Main Content
(The primary deliverable — comprehensive and detailed)
## Variations
(2-3 alternative approaches or versions)
## Implementation Notes
(How to use this output effectively)
## Quality Checklist
(Self-assessment against best practices)"""),
    ]
    
    from lib.routing import resolve_from_env_or_config as _resolve
    provider, model, _cost = _resolve("moderate")
    cost = estimate_cost()
    print(f"    [budget] alias=premium model={model} cost=${cost} remaining=${state['context']['budget_state']['remaining']:.3f}")
    
    content, error = call_llm(messages)
    if error or not content:
        return {**state, "error": str(error or "Empty LLM response")}
    
    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": content, "cost": state.get("cost", 0) + cost}


def step_3_critic(state):
    output = state.get("generated_output", "")
    if not output or len(output) < 50:
        return {**state, "quality_score": 0.0, "critic_feedback": "Output too short"}
    
    # Heuristic pre-score
    score = 5.0
    if len(output) > 200: score += 0.5
    if len(output) > 500: score += 0.5
    if "##" in output: score += 0.5
    if "- " in output or "1." in output: score += 0.5
    if len(output) > 1000: score += 0.5
    score = min(score, 10.0)
    
    feedback = ""
    
    # LLM critic if heuristic score is below threshold (Fix #1)
    if score < 9.5:
        print(f"    [critic] Heuristic score {score:.1f} < 7.0 — running LLM critic")
        llm_score, feedback = call_cheap_critic(output, state.get("step_1_output", ""))
        cost = estimate_cost()
        state["context"]["budget_state"]["remaining"] -= cost
        score = (score + llm_score) / 2  # Average heuristic + LLM
        state = {**state, "cost": state.get("cost", 0) + cost}
        print(f"    [critic] LLM score: {llm_score:.1f}, combined: {score:.1f}")
    
    return {**state, "quality_score": score, "critic_feedback": feedback, "final_output": output}


def should_retry(state):
    """Decide: retry generation or proceed to artifact (Fix #3)."""
    score = state.get("quality_score", 0)
    retries = state.get("retry_count", 0)
    if score < 9.0 and retries < 4:
        print(f"    [retry] Score {score:.1f} < 6.0, retrying (attempt {retries + 1})")
        return "retry"
    return "accept"


def step_retry(state):
    """Increment retry counter and loop back."""
    return {**state, "retry_count": state.get("retry_count", 0) + 1}


def step_5_artifact(state):
    output = state.get("final_output", state.get("generated_output", ""))
    wf_id = state["context"]["workflow_id"]
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    
    md_name = f"k41-ad-campaign-builder_{wf_id}_{ts}.md"
    md_path = OUTPUTS_DIR / md_name
    md_path.write_text(output)
    print(f"  [artifact] Written to: {md_path}")
    
    # Composable envelope with actual results (Fix #2)
    env_name = f"k41-ad-campaign-builder_{wf_id}_{ts}_envelope.json"
    env_path = OUTPUTS_DIR / env_name
    
    # Extract key points for downstream skills
    key_points = []
    for line in output.split("\n"):
        line = line.strip()
        if line.startswith("- ") or line.startswith("1.") or line.startswith("* "):
            key_points.append(line.lstrip("- *0123456789.").strip())
        if len(key_points) >= 10:
            break
    
    envelope = {
        "skill_id": "k41-ad-campaign-builder",
        "workflow_id": wf_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "outputs": {
            "result": output,
            "result_summary": output[:300],
            "key_points": key_points,
            "skill_type": "generator",
            "metadata": {
                "quality_score": state.get("quality_score", 0),
                "retries": state.get("retry_count", 0),
                "cost": state.get("cost", 0),
                "model": __import__("lib.routing", fromlist=["resolve_from_env_or_config"]).resolve_from_env_or_config("moderate")[1],
            },
        },
        "artifact_path": str(md_path),
        "quality_score": state.get("quality_score", 0),
        "cost": state.get("cost", 0),
    }
    env_path.write_text(json.dumps(envelope, indent=2, default=str))
    print(f"  [envelope] Written to: {env_path}")
    
    return {**state, "artifact_path": str(md_path), "envelope_path": str(env_path)}


# ── Graph (with retry loop — Fix #3) ──────────────────────────────────

def build_graph():
    graph = StateGraph(SkillState)
    graph.add_node("step_1", step_1_parse)
    graph.add_node("step_2", step_2_generate)
    graph.add_node("step_3", step_3_critic)
    graph.add_node("step_retry", step_retry)
    graph.add_node("step_5", step_5_artifact)
    graph.set_entry_point("step_1")
    graph.add_edge("step_1", "step_2")
    graph.add_edge("step_2", "step_3")
    graph.add_conditional_edges("step_3", should_retry, {
        "retry": "step_retry",
        "accept": "step_5",
    })
    graph.add_edge("step_retry", "step_2")
    graph.add_edge("step_5", END)
    return graph


# ── Main ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", default="k41-ad-campaign-builder")
    parser.add_argument("--input", nargs=2, action="append", metavar=("KEY", "VALUE"))
    parser.add_argument("--thread-id", default=None)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--input-from", default=None)
    parser.add_argument("--force", action="store_true", help="Overwrite existing outputs")
    args = parser.parse_args()
    
    spec = load_spec(args)
    validate_inputs(spec)
    
    wf_id = spec["context"]["workflow_id"]
    
    # Idempotency check (Fix #6)
    if not args.force:
        existing = list(OUTPUTS_DIR.glob(f"k41-ad-campaign-builder_*_envelope.json"))
        if existing:
            latest = sorted(existing)[-1]
            print(f"\nSkip: Output already exists ({latest.name})")
            print(f"Use --force to regenerate.")
            sys.exit(0)
    
    print(f"\nStarting skill: Ad Campaign Builder v1.0.0")
    print(f"Thread ID: {wf_id}")
    
    graph = build_graph()
    conn = sqlite3.connect(str(CHECKPOINT_DB), check_same_thread=False)
    checkpointer = SqliteSaver(conn)
    app = graph.compile(checkpointer=checkpointer)
    
    initial_state = {
        "inputs": spec["inputs"],
        "context": spec["context"],
        "step_1_output": "",
        "generated_output": "",
        "quality_score": 0.0,
        "critic_feedback": "",
        "retry_count": 0,
        "final_output": "",
        "artifact_path": "",
        "envelope_path": "",
        "error": "",
        "cost": 0.0,
    }
    
    config = {"configurable": {"thread_id": wf_id}}
    
    for step in app.stream(initial_state, config):
        for node_name, node_state in step.items():
            print(f"\n  [node] {node_name}")
            if node_state.get("error"):
                print(f"  [error] {node_state['error']}")
                break
            print(f"  [done] {node_name}")
    
    final = app.get_state(config)
    if final and final.values:
        vals = final.values
        if vals.get("artifact_path"):
            print(f"\nSkill complete: Ad Campaign Builder")
            print(f"Thread ID: {wf_id}")
            print(f"Output: {vals['artifact_path']}")
            print(f"Quality: {vals.get('quality_score', 0):.1f}/10")
            print(f"Cost: ${vals.get('cost', 0):.3f}")
        elif vals.get("error"):
            print(f"\nERROR: Skill failed — {vals['error']}")
    
    conn.close()
