#!/usr/bin/env python3
"""
NemoClaw Skill — Multi-Touch Sequence Builder v1.0.0 (out-01-multi-touch-sequence-builder)
Full 7-day sequence: Day 1 email → Day 2 LinkedIn view → Day 3 connect → Day 5 follow-up → Day 7 objection handler → Day 10 break-up email.
Generated by NemoClaw E-9. LangGraph v4.0 + SqliteSaver.
"""
import argparse, json, os, sys, time, sqlite3
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SKILL_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = SKILL_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root for lib.routing

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from typing import TypedDict

CHECKPOINT_DB = Path.home() / ".nemoclaw" / "checkpoints" / "langgraph.db"
CHECKPOINT_DB.parent.mkdir(parents=True, exist_ok=True)


class SkillState(TypedDict):
    inputs: dict; context: dict; step_1_output: str; generated_output: str
    quality_score: float; critic_feedback: str; retry_count: int; final_output: str
    artifact_path: str; envelope_path: str; error: str; cost: float


def call_llm(messages, max_tokens=4000):
    from lib.routing import call_llm as _routed_call
    return _routed_call(messages, task_class="complex_reasoning", max_tokens=max_tokens)

def estimate_cost(task_class="moderate"):
    from lib.routing import estimate_cost as _est
    return _est(task_class)

def load_spec(args):
    spec = {"inputs": {}, "context": {"workflow_id": args.thread_id or f"skill-out-01-multi-touch-sequence-builder-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}-{os.urandom(4).hex()}", "budget_state": {"remaining": 20.0}, "step_history": []}}
    if args.input:
        for pair in args.input: spec["inputs"][pair[0]] = pair[1]
    if args.input_from:
        ep = Path(args.input_from)
        if ep.exists(): spec["inputs"].update(json.loads(ep.read_text()).get("outputs", {}))
    return spec

def validate_inputs(spec):
    errors = []
    # Sanitize all inputs
    for key in list(spec.get("inputs", {}).keys()):
        val = spec["inputs"][key]
        if not isinstance(val, str):
            spec["inputs"][key] = str(val)
        # Strip dangerous characters
        spec["inputs"][key] = spec["inputs"][key].replace("\x00", "").strip()
        # Length cap (prevent memory abuse)
        if len(spec["inputs"][key]) > 50000:
            spec["inputs"][key] = spec["inputs"][key][:50000]
    if not spec["inputs"].get("prospect_profile") or len(spec["inputs"]["prospect_profile"]) < 20:
        errors.append("Missing required input: prospect_profile")
    if not spec["inputs"].get("value_prop") or len(spec["inputs"]["value_prop"]) < 10:
        errors.append("Missing required input: value_prop")
    if errors:
        for e in errors: print(f"  ERROR: {e}")
        sys.exit(1)

def step_1_parse(state):
    prospect_profile = spec["inputs"].get("prospect_profile", "")
    value_prop = spec["inputs"].get("value_prop", "")
    context = f"""Task: Multi-Touch Sequence Builder
- prospect_profile: {prospect_profile}
- value_prop: {value_prop}"""
    return {**state, "step_1_output": context}

def step_2_generate(state):
    context = state["step_1_output"]
    feedback = state.get("critic_feedback", "")
    fb = f"\n\nPrevious feedback (improve):\n{feedback}" if feedback else ""
    messages = [("system", """You are a multi-channel outreach strategist. Design sequences that combine email, LinkedIn, and follow-ups into a cohesive conversion journey."""), ("human", f"""{context}{fb}""")]
    from lib.routing import resolve_from_env_or_config as _resolve
    provider, model, _cost = _resolve("complex_reasoning")
    cost = estimate_cost()
    content, error = call_llm(messages)
    if error or not content: return {**state, "error": str(error or "Empty response")}
    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": content, "cost": state.get("cost", 0) + cost}

def step_3_critic(state):
    output = state.get("generated_output", "")
    if not output or len(output) < 50: return {**state, "quality_score": 0.0, "critic_feedback": "Too short"}
    score = 5.0
    if len(output) > 200: score += 0.5
    if len(output) > 500: score += 0.5
    if "##" in output: score += 0.5
    if "- " in output or "1." in output: score += 0.5
    if len(output) > 1000: score += 0.5
    feedback = ""
    if score < 7.0:
        try:
            from langchain_anthropic import ChatAnthropic
            from lib.routing import resolve_alias as _ra
            _cp, _cm, _cc = _ra("structured_short")
            resp = ChatAnthropic(model=_cm, max_tokens=300).invoke([("system","Score 1-10 as JSON: {\"score\":N,\"feedback\":\"...\"}"),("human",f"Task: Multi-Touch Sequence Builder\n\nOutput:\n{output[:2000]}")])
            text = resp.content.strip()
            if "{" in text:
                data = json.loads(text[text.index("{"):text.rindex("}")+2])
                llm_score = data.get("score", 5); feedback = data.get("feedback", "")
                score = (score + llm_score) / 2
                state = {**state, "cost": state.get("cost", 0) + 0.008}
        except Exception as _critic_err:
            import logging; logging.getLogger("nemoclaw.critic").warning(f"Critic call failed: {_critic_err}")
    return {**state, "quality_score": min(score, 10.0), "critic_feedback": feedback, "final_output": output}

def should_retry(state):
    if state.get("quality_score", 0) < 6.0 and state.get("retry_count", 0) < 1: return "retry"
    return "accept"

def step_retry(state): return {**state, "retry_count": state.get("retry_count", 0) + 1}

def step_5_artifact(state):
    output = state.get("final_output", state.get("generated_output", ""))
    wf_id = state["context"]["workflow_id"]
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    md_path = OUTPUTS_DIR / f"out-01-multi-touch-sequence-builder_{wf_id}_{ts}.md"
    md_path.write_text(output)
    key_points = [l.lstrip("- *0123456789.").strip() for l in output.split("\n") if l.strip().startswith(("- ","1.","* "))][:10]
    env_path = OUTPUTS_DIR / f"out-01-multi-touch-sequence-builder_{wf_id}_{ts}_envelope.json"
    envelope = {"skill_id": "out-01-multi-touch-sequence-builder", "workflow_id": wf_id, "timestamp": datetime.now(timezone.utc).isoformat(),
        "outputs": {"result": output, "result_summary": output[:300], "key_points": key_points, "skill_type": "generator",
            "metadata": {"quality_score": state.get("quality_score", 0), "retries": state.get("retry_count", 0), "cost": state.get("cost", 0), "model": __import__("lib.routing", fromlist=["resolve_from_env_or_config"]).resolve_from_env_or_config("complex_reasoning")[1]}},
        "artifact_path": str(md_path), "quality_score": state.get("quality_score", 0), "cost": state.get("cost", 0)}
    env_path.write_text(json.dumps(envelope, indent=2, default=str))
    return {**state, "artifact_path": str(md_path), "envelope_path": str(env_path)}

def build_graph():
    g = StateGraph(SkillState)
    g.add_node("step_1", step_1_parse); g.add_node("step_2", step_2_generate); g.add_node("step_3", step_3_critic)
    g.add_node("step_retry", step_retry); g.add_node("step_5", step_5_artifact)
    g.set_entry_point("step_1"); g.add_edge("step_1", "step_2"); g.add_edge("step_2", "step_3")
    g.add_conditional_edges("step_3", should_retry, {"retry": "step_retry", "accept": "step_5"})
    g.add_edge("step_retry", "step_2"); g.add_edge("step_5", END)
    return g

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", default="out-01-multi-touch-sequence-builder"); parser.add_argument("--input", nargs=2, action="append")
    parser.add_argument("--thread-id", default=None); parser.add_argument("--resume", action="store_true")
    parser.add_argument("--input-from", default=None); parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    spec = load_spec(args); validate_inputs(spec)
    wf_id = spec["context"]["workflow_id"]
    if not args.force:
        existing = list(OUTPUTS_DIR.glob(f"out-01-multi-touch-sequence-builder_*_envelope.json"))
        if existing: print(f"Skip: Output exists ({sorted(existing)[-1].name}). Use --force."); sys.exit(0)
    print(f"\nStarting: Multi-Touch Sequence Builder v1.0.0\nThread: {wf_id}")
    graph = build_graph(); conn = sqlite3.connect(str(CHECKPOINT_DB), check_same_thread=False); ckpt = SqliteSaver(conn)
    app = graph.compile(checkpointer=ckpt)
    init = {"inputs": spec["inputs"], "context": spec["context"], "step_1_output": "", "generated_output": "",
        "quality_score": 0.0, "critic_feedback": "", "retry_count": 0, "final_output": "", "artifact_path": "",
        "envelope_path": "", "error": "", "cost": 0.0}
    config = {"configurable": {"thread_id": wf_id}}
    for step in app.stream(init, config):
        for nn, ns in step.items():
            if ns.get("error"): print(f"  [error] {ns['error']}"); break
    final = app.get_state(config)
    if final and final.values:
        v = final.values
        if v.get("artifact_path"): print(f"\nComplete: Multi-Touch Sequence Builder\nOutput: {v['artifact_path']}\nQuality: {v.get('quality_score',0):.1f}/10\nCost: ${v.get('cost',0):.3f}")
        elif v.get("error"): print(f"\nFAILED: {v['error']}")
    conn.close()
