#!/usr/bin/env python3
"""
NemoClaw Skill — Subscription Manager v1.0.0 (k59-subscription-manager)

Subscription lifecycle management — renewals, upgrades, downgrades, churn prediction, plan changes.

Generated by NemoClaw Skill Factory (E-5/E-6).
Runner: LangGraph v4.0 + SqliteSaver
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# -- Paths -----------------------------------------------------------------

REPO = Path(__file__).resolve().parents[1]
SKILL_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = SKILL_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root for lib.routing

# -- LangGraph -------------------------------------------------------------

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from typing import TypedDict
import sqlite3

CHECKPOINT_DB = Path.home() / ".nemoclaw" / "checkpoints" / "langgraph.db"
CHECKPOINT_DB.parent.mkdir(parents=True, exist_ok=True)

SKILL_ID = "k59-subscription-manager"


class SkillState(TypedDict):
    inputs: dict
    context: dict
    step_1_output: str
    generated_output: str
    quality_score: float
    critic_feedback: str
    retry_count: int
    final_output: str
    artifact_path: str
    envelope_path: str
    error: str
    cost: float

# -- LLM Helpers -----------------------------------------------------------


def call_llm(messages, max_tokens=4000):
    from lib.routing import call_llm as _routed_call
    return _routed_call(messages, task_class="moderate", max_tokens=max_tokens)


def call_cheap_critic(output_text, task_description):
    messages = [
        ("system", "You are a strict quality evaluator. Score 1-10: 9-10=excellent (comprehensive, well-structured, actionable, professional-grade), 7-8=good (solid but missing depth), 5-6=acceptable, 1-4=poor. Be generous with detailed, well-structured outputs. Return ONLY JSON: {\"score\": N, \"feedback\": \"...\"}"),
        ("human", f"Task: {task_description}\n\nOutput to evaluate:\n{output_text[:2000]}"),
    ]
    try:
        from lib.routing import call_llm
        _critic_text, _critic_err = call_llm(messages, "structured_short", 300)
        text = _critic_text.strip() if _critic_text else ""
        if "{" in text:
            json_str = text[text.index("{"):text.rindex("}") + 1]
            data = json.loads(json_str)
            return data.get("score", 5), data.get("feedback", "")
    except Exception:
        pass
    return 5.0, "Critic unavailable"


def estimate_cost(task_class="moderate"):
    from lib.routing import estimate_cost as _est
    return _est(task_class)


# -- Skill Spec ------------------------------------------------------------


def load_spec(args):
    spec = {
        "inputs": {},
        "context": {
            "workflow_id": args.thread_id or f"skill-{SKILL_ID}-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}-{os.urandom(4).hex()}",
            "budget_state": {"remaining": 20.0},
            "step_history": [],
        },
    }
    if args.input:
        for pair in args.input:
            spec["inputs"][pair[0]] = pair[1]
    if args.input_from:
        envelope_path = Path(args.input_from)
        if envelope_path.exists():
            envelope = json.loads(envelope_path.read_text())
            spec["inputs"].update(envelope.get("outputs", {}))
    return spec


def validate_inputs(spec):
    errors = []
    if not spec["inputs"].get("subscription_data") or len(spec["inputs"]["subscription_data"]) < 20:
        errors.append("Missing required input: subscription_data (min 20 chars)")
    allowed_actions = ["renewal_check", "churn_prediction", "upgrade_recommendation", "plan_optimization"]
    if not spec["inputs"].get("action") or spec["inputs"]["action"] not in allowed_actions:
        errors.append(f"Missing or invalid input: action (must be one of {allowed_actions})")
    if errors:
        print("ERROR: Input validation failed:")
        for e in errors:
            print(f"  {e}")
        sys.exit(1)


# -- Steps -----------------------------------------------------------------


def step_1_parse(state):
    subscription_data = spec["inputs"].get("subscription_data", "")
    action = spec["inputs"].get("action", "")
    customer_id = spec["inputs"].get("customer_id", "")
    lookback_days = spec["inputs"].get("lookback_days", "30")

    context = f"""Task: Subscription Lifecycle Management
- action: {action}
- customer_id: {customer_id}
- lookback_days: {lookback_days}
- subscription_data: {subscription_data}"""

    return {**state, "step_1_output": context}


def step_2_analyze_patterns(state):
    context = state["step_1_output"]
    feedback = state.get("critic_feedback", "")

    feedback_section = ""
    if feedback:
        feedback_section = f"\n\nPrevious attempt feedback (improve on this):\n{feedback}"

    messages = [
        ("system", "You are an expert subscription revenue analyst specializing in SaaS lifecycle management, churn prediction, and revenue optimization."),
        ("human", f"""{context}{feedback_section}

Analyze subscription health for the requested action. Produce a comprehensive analysis:
## MRR Trends
(Monthly recurring revenue trajectory, growth/contraction signals)
## Churn Signals
(Early warning indicators — usage decline, support tickets, payment failures, engagement decay)
## Usage Patterns
(Feature adoption, login frequency, API usage, seat utilization)
## Payment History
(On-time payments, failed charges, downgrades, discount requests)
## Engagement Decay Analysis
(Week-over-week engagement trends, feature abandonment, inactive periods)"""),
    ]

    from lib.routing import resolve_from_env_or_config as _resolve
    provider, model, _cost = _resolve("moderate")
    cost = estimate_cost()
    print(f"    [budget] alias=moderate model={model} cost=${cost} remaining=${state['context']['budget_state']['remaining']:.3f}")

    content, error = call_llm(messages)
    if error or not content:
        return {**state, "error": str(error or "Empty LLM response")}

    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": content, "cost": state.get("cost", 0) + cost}


def step_3_generate_recommendations(state):
    prev_output = state.get("generated_output", "")
    context = state["step_1_output"]

    messages = [
        ("system", "You are an expert subscription revenue optimizer who generates specific, actionable recommendations for subscription lifecycle management."),
        ("human", f"""{context}

Previous analysis:
{prev_output[:3000]}

Generate specific actionable recommendations:
## Renewal Timing
(Optimal renewal outreach timing per account, early renewal incentives, contract extension strategies)
## Upsell Opportunities
(Upgrade paths, add-on recommendations, usage-based expansion triggers)
## At-Risk Interventions
(Specific actions for each at-risk account — discount offers, feature unlocks, executive outreach)
## Plan Optimization
(Right-sizing recommendations, custom plan suggestions, bundling opportunities)
## Pricing Adjustment Recommendations
(Price increase candidates, grandfathering strategy, value-metric alignment)"""),
    ]

    cost = estimate_cost()
    content, error = call_llm(messages, max_tokens=4000)
    if error or not content:
        return {**state, "error": str(error or "Empty LLM response")}

    combined = prev_output + "\n\n---\n\n" + content
    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": combined, "cost": state.get("cost", 0) + cost}


def step_4_critic(state):
    output = state.get("generated_output", "")
    if not output or len(output) < 50:
        return {**state, "quality_score": 0.0, "critic_feedback": "Output too short"}

    score = 5.0
    if len(output) > 200: score += 0.5
    if len(output) > 500: score += 0.5
    if "##" in output: score += 0.5
    if "- " in output or "1." in output: score += 0.5
    if len(output) > 1000: score += 0.5
    score = min(score, 10.0)

    feedback = ""
    if score < 9.5:
        print(f"    [critic] Heuristic score {score:.1f} < 9.5 — running LLM critic")
        llm_score, feedback = call_cheap_critic(output, state.get("step_1_output", ""))
        cost = estimate_cost()
        state["context"]["budget_state"]["remaining"] -= cost
        score = llm_score
        state = {**state, "cost": state.get("cost", 0) + cost}
        print(f"    [critic] LLM score: {llm_score:.1f}, final: {score:.1f}")

    return {**state, "quality_score": score, "critic_feedback": feedback, "final_output": output}


def should_retry(state):
    score = state.get("quality_score", 0)
    retries = state.get("retry_count", 0)
    if score < 9.0 and retries < 4:
        print(f"    [retry] Score {score:.1f} < 9.0, retrying (attempt {retries + 1})")
        return "retry"
    return "accept"


def step_retry(state):
    return {**state, "retry_count": state.get("retry_count", 0) + 1}


def step_5_artifact(state):
    output = state.get("final_output", state.get("generated_output", ""))
    wf_id = state["context"]["workflow_id"]
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    md_name = f"{SKILL_ID}_{wf_id}_{ts}.md"
    md_path = OUTPUTS_DIR / md_name
    md_path.write_text(output)
    print(f"  [artifact] Written to: {md_path}")

    env_name = f"{SKILL_ID}_{wf_id}_{ts}_envelope.json"
    env_path = OUTPUTS_DIR / env_name

    key_points = []
    for line in output.split("\n"):
        line = line.strip()
        if line.startswith("- ") or line.startswith("1.") or line.startswith("* "):
            key_points.append(line.lstrip("- *0123456789.").strip())
        if len(key_points) >= 10:
            break

    envelope = {
        "skill_id": SKILL_ID,
        "workflow_id": wf_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "outputs": {
            "result": output,
            "result_summary": output[:300],
            "key_points": key_points,
            "skill_type": "executor",
            "metadata": {
                "quality_score": state.get("quality_score", 0),
                "retries": state.get("retry_count", 0),
                "cost": state.get("cost", 0),
                "model": __import__("lib.routing", fromlist=["resolve_from_env_or_config"]).resolve_from_env_or_config("moderate")[1],
            },
        },
        "artifact_path": str(md_path),
        "quality_score": state.get("quality_score", 0),
        "cost": state.get("cost", 0),
    }
    env_path.write_text(json.dumps(envelope, indent=2, default=str))
    print(f"  [envelope] Written to: {env_path}")

    return {**state, "artifact_path": str(md_path), "envelope_path": str(env_path)}


# -- Graph -----------------------------------------------------------------


def build_graph():
    graph = StateGraph(SkillState)
    graph.add_node("step_1", step_1_parse)
    graph.add_node("step_2", step_2_analyze_patterns)
    graph.add_node("step_3", step_3_generate_recommendations)
    graph.add_node("step_4", step_4_critic)
    graph.add_node("step_retry", step_retry)
    graph.add_node("step_5", step_5_artifact)
    graph.set_entry_point("step_1")
    graph.add_edge("step_1", "step_2")
    graph.add_edge("step_2", "step_3")
    graph.add_edge("step_3", "step_4")
    graph.add_conditional_edges("step_4", should_retry, {
        "retry": "step_retry",
        "accept": "step_5",
    })
    graph.add_edge("step_retry", "step_2")
    graph.add_edge("step_5", END)
    return graph


# -- Main ------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", default=SKILL_ID)
    parser.add_argument("--input", nargs=2, action="append", metavar=("KEY", "VALUE"))
    parser.add_argument("--thread-id", default=None)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--input-from", default=None)
    parser.add_argument("--force", action="store_true", help="Overwrite existing outputs")
    args = parser.parse_args()

    spec = load_spec(args)
    validate_inputs(spec)

    wf_id = spec["context"]["workflow_id"]

    if not args.force:
        existing = list(OUTPUTS_DIR.glob(f"{SKILL_ID}_*_envelope.json"))
        if existing:
            latest = sorted(existing)[-1]
            print(f"\nSkip: Output already exists ({latest.name})")
            print(f"Use --force to regenerate.")
            sys.exit(0)

    print(f"\nStarting skill: Subscription Manager v1.0.0")
    print(f"Thread ID: {wf_id}")

    graph = build_graph()
    conn = sqlite3.connect(str(CHECKPOINT_DB), check_same_thread=False)
    checkpointer = SqliteSaver(conn)
    app = graph.compile(checkpointer=checkpointer)

    initial_state = {
        "inputs": spec["inputs"],
        "context": spec["context"],
        "step_1_output": "",
        "generated_output": "",
        "quality_score": 0.0,
        "critic_feedback": "",
        "retry_count": 0,
        "final_output": "",
        "artifact_path": "",
        "envelope_path": "",
        "error": "",
        "cost": 0.0,
    }

    config = {"configurable": {"thread_id": wf_id}}

    for step in app.stream(initial_state, config):
        for node_name, node_state in step.items():
            print(f"\n  [node] {node_name}")
            if node_state.get("error"):
                print(f"  [error] {node_state['error']}")
                break
            print(f"  [done] {node_name}")

    final = app.get_state(config)
    if final and final.values:
        vals = final.values
        if vals.get("artifact_path"):
            print(f"\nSkill complete: Subscription Manager")
            print(f"Thread ID: {wf_id}")
            print(f"Output: {vals['artifact_path']}")
            print(f"Quality: {vals.get('quality_score', 0):.1f}/10")
            print(f"Cost: ${vals.get('cost', 0):.3f}")
        elif vals.get("error"):
            print(f"\nERROR: Skill failed — {vals['error']}")

    conn.close()
