#!/usr/bin/env python3
"""
NemoClaw Skill — NDA Generator v1.0.0 (k57-nda-generator)

Generate NDA (Non-Disclosure Agreement) documents from party details.

Generated by NemoClaw Skill Factory (E-5/E-6).
Runner: LangGraph v4.0 + SqliteSaver
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# -- Paths -----------------------------------------------------------------

REPO = Path(__file__).resolve().parents[1]
SKILL_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = SKILL_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root for lib.routing

# -- LangGraph -------------------------------------------------------------

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from typing import TypedDict
import sqlite3

CHECKPOINT_DB = Path.home() / ".nemoclaw" / "checkpoints" / "langgraph.db"
CHECKPOINT_DB.parent.mkdir(parents=True, exist_ok=True)

SKILL_ID = "k57-nda-generator"


class SkillState(TypedDict):
    inputs: dict
    context: dict
    step_1_output: str
    generated_output: str
    quality_score: float
    critic_feedback: str
    retry_count: int
    final_output: str
    artifact_path: str
    envelope_path: str
    error: str
    cost: float

# -- LLM Helpers -----------------------------------------------------------


def call_llm(messages, max_tokens=4000):
    from lib.routing import call_llm_or_chain
    return call_llm_or_chain(messages, task_class="moderate", task_domain="legal_contracts", max_tokens=max_tokens)


def call_cheap_critic(output_text, task_description):
    messages = [
        ("system", "You are a strict quality evaluator. Score 1-10: 9-10=excellent (comprehensive, well-structured, actionable, professional-grade), 7-8=good (solid but missing depth), 5-6=acceptable, 1-4=poor. Be generous with detailed, well-structured outputs. Return ONLY JSON: {\"score\": N, \"feedback\": \"...\"}"),
        ("human", f"Task: {task_description}\n\nOutput to evaluate:\n{output_text[:2000]}"),
    ]
    try:
        from lib.routing import call_llm
        _critic_text, _critic_err = call_llm(messages, "structured_short", 300)
        text = _critic_text.strip() if _critic_text else ""
        if "{" in text:
            json_str = text[text.index("{"):text.rindex("}") + 1]
            data = json.loads(json_str)
            return data.get("score", 5), data.get("feedback", "")
    except Exception:
        pass
    return 5.0, "Critic unavailable"


def estimate_cost(task_class="moderate"):
    from lib.routing import estimate_cost as _est
    return _est(task_class)


# -- Skill Spec ------------------------------------------------------------


def load_spec(args):
    spec = {
        "inputs": {},
        "context": {
            "workflow_id": args.thread_id or f"skill-{SKILL_ID}-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}-{os.urandom(4).hex()}",
            "budget_state": {"remaining": 20.0},
            "step_history": [],
        },
    }
    if args.input:
        for pair in args.input:
            spec["inputs"][pair[0]] = pair[1]
    if args.input_from:
        envelope_path = Path(args.input_from)
        if envelope_path.exists():
            envelope = json.loads(envelope_path.read_text())
            spec["inputs"].update(envelope.get("outputs", {}))
    return spec


def validate_inputs(spec):
    errors = []
    if not spec["inputs"].get("disclosing_party") or len(spec["inputs"]["disclosing_party"]) < 5:
        errors.append("Missing required input: disclosing_party")
    if not spec["inputs"].get("receiving_party") or len(spec["inputs"]["receiving_party"]) < 5:
        errors.append("Missing required input: receiving_party")
    if errors:
        print("ERROR: Input validation failed:")
        for e in errors:
            print(f"  {e}")
        sys.exit(1)


# -- Steps -----------------------------------------------------------------


def step_1_parse(state):
    disclosing_party = spec["inputs"].get("disclosing_party", "")
    receiving_party = spec["inputs"].get("receiving_party", "")
    jurisdiction = spec["inputs"].get("jurisdiction", "Jordan")
    nda_type = spec["inputs"].get("nda_type", "mutual")
    confidential_scope = spec["inputs"].get("confidential_scope", "")
    duration_months = spec["inputs"].get("duration_months", "24")

    context = f"""Task: NDA Generation
- disclosing_party: {disclosing_party}
- receiving_party: {receiving_party}
- jurisdiction: {jurisdiction}
- nda_type: {nda_type}
- confidential_scope: {confidential_scope}
- duration_months: {duration_months}"""

    return {**state, "step_1_output": context}


def step_2_draft_nda(state):
    context = state["step_1_output"]
    feedback = state.get("critic_feedback", "")

    feedback_section = ""
    if feedback:
        feedback_section = f"\n\nPrevious attempt feedback (improve on this):\n{feedback}"

    messages = [
        ("system", "You are a legal document specialist focusing on NDA drafting. Create clear, enforceable non-disclosure agreements with appropriate protections for all parties."),
        ("human", f"""{context}{feedback_section}

Draft a complete, professional NDA document:
## NON-DISCLOSURE AGREEMENT
(Full legal title with date placeholder)
## 1. PARTIES
(Complete identification of all parties with addresses)
## 2. DEFINITIONS
(Confidential Information, Disclosing Party, Receiving Party, Representatives)
## 3. SCOPE OF CONFIDENTIAL INFORMATION
(What is covered, exclusions, marking requirements)
## 4. OBLIGATIONS OF RECEIVING PARTY
(Non-disclosure, limited use, standard of care, return/destruction)
## 5. EXCLUSIONS FROM CONFIDENTIALITY
(Publicly available, independently developed, prior knowledge, court-ordered)
## 6. TERM AND TERMINATION
(Duration, survival period, termination rights)
## 7. REMEDIES
(Injunctive relief, damages, indemnification)
## 8. GOVERNING LAW AND DISPUTE RESOLUTION
(Jurisdiction-specific law, arbitration/mediation clause)
## 9. GENERAL PROVISIONS
(Entire agreement, amendments, severability, waiver, assignment)
## 10. SIGNATURES
(Signature blocks for all parties with date and title lines)"""),
    ]

    from lib.routing import resolve_from_env_or_config as _resolve
    provider, model, _cost = _resolve("moderate")
    cost = estimate_cost()
    print(f"    [budget] alias=moderate model={model} cost=${cost} remaining=${state['context']['budget_state']['remaining']:.3f}")

    content, error = call_llm(messages, max_tokens=4000)
    if error or not content:
        return {**state, "error": str(error or "Empty LLM response")}

    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": content, "cost": state.get("cost", 0) + cost}


def step_3_critic(state):
    output = state.get("generated_output", "")
    if not output or len(output) < 50:
        return {**state, "quality_score": 0.0, "critic_feedback": "Output too short"}

    score = 5.0
    if len(output) > 200: score += 0.5
    if len(output) > 500: score += 0.5
    if "##" in output: score += 0.5
    if "- " in output or "1." in output: score += 0.5
    if len(output) > 1000: score += 0.5
    score = min(score, 10.0)

    feedback = ""
    if score < 10.5:
        print(f"    [critic] Heuristic score {score:.1f} < 10.5 — running LLM critic")
        llm_score, feedback = call_cheap_critic(output, state.get("step_1_output", ""))
        cost = estimate_cost()
        state["context"]["budget_state"]["remaining"] -= cost
        score = llm_score
        state = {**state, "cost": state.get("cost", 0) + cost}
        print(f"    [critic] LLM score: {llm_score:.1f}, final: {score:.1f}")

    return {**state, "quality_score": score, "critic_feedback": feedback, "final_output": output}


def should_retry(state):
    score = state.get("quality_score", 0)
    retries = state.get("retry_count", 0)
    if score < 10.0 and retries < 5:
        print(f"    [retry] Score {score:.1f} < 10.0, retrying (attempt {retries + 1})")
        return "retry"
    return "accept"


def step_retry(state):
    return {**state, "retry_count": state.get("retry_count", 0) + 1}


def step_4_artifact(state):
    output = state.get("final_output", state.get("generated_output", ""))
    wf_id = state["context"]["workflow_id"]
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    md_name = f"{SKILL_ID}_{wf_id}_{ts}.md"
    md_path = OUTPUTS_DIR / md_name
    md_path.write_text(output)
    print(f"  [artifact] Written to: {md_path}")

    env_name = f"{SKILL_ID}_{wf_id}_{ts}_envelope.json"
    env_path = OUTPUTS_DIR / env_name

    key_points = []
    for line in output.split("\n"):
        line = line.strip()
        if line.startswith("- ") or line.startswith("1.") or line.startswith("* "):
            key_points.append(line.lstrip("- *0123456789.").strip())
        if len(key_points) >= 10:
            break

    envelope = {
        "skill_id": SKILL_ID,
        "workflow_id": wf_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "outputs": {
            "result": output,
            "result_summary": output[:300],
            "key_points": key_points,
            "skill_type": "generator",
            "metadata": {
                "quality_score": state.get("quality_score", 0),
                "retries": state.get("retry_count", 0),
                "cost": state.get("cost", 0),
                "model": __import__("lib.routing", fromlist=["resolve_from_env_or_config"]).resolve_from_env_or_config("moderate")[1],
            },
        },
        "artifact_path": str(md_path),
        "quality_score": state.get("quality_score", 0),
        "cost": state.get("cost", 0),
    }
    env_path.write_text(json.dumps(envelope, indent=2, default=str))
    print(f"  [envelope] Written to: {env_path}")

    return {**state, "artifact_path": str(md_path), "envelope_path": str(env_path)}


# -- Graph -----------------------------------------------------------------


def build_graph():
    graph = StateGraph(SkillState)
    graph.add_node("step_1", step_1_parse)
    graph.add_node("step_2", step_2_draft_nda)
    graph.add_node("step_3", step_3_critic)
    graph.add_node("step_retry", step_retry)
    graph.add_node("step_4", step_4_artifact)
    graph.set_entry_point("step_1")
    graph.add_edge("step_1", "step_2")
    graph.add_edge("step_2", "step_3")
    graph.add_conditional_edges("step_3", should_retry, {
        "retry": "step_retry",
        "accept": "step_4",
    })
    graph.add_edge("step_retry", "step_2")
    graph.add_edge("step_4", END)
    return graph


# -- Main ------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", default=SKILL_ID)
    parser.add_argument("--input", nargs=2, action="append", metavar=("KEY", "VALUE"))
    parser.add_argument("--thread-id", default=None)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--input-from", default=None)
    parser.add_argument("--force", action="store_true", help="Overwrite existing outputs")
    args = parser.parse_args()

    spec = load_spec(args)
    validate_inputs(spec)

    wf_id = spec["context"]["workflow_id"]

    if not args.force:
        existing = list(OUTPUTS_DIR.glob(f"{SKILL_ID}_*_envelope.json"))
        if existing:
            latest = sorted(existing)[-1]
            print(f"\nSkip: Output already exists ({latest.name})")
            print(f"Use --force to regenerate.")
            sys.exit(0)

    print(f"\nStarting skill: NDA Generator v1.0.0")
    print(f"Thread ID: {wf_id}")

    graph = build_graph()
    conn = sqlite3.connect(str(CHECKPOINT_DB), check_same_thread=False)
    checkpointer = SqliteSaver(conn)
    app = graph.compile(checkpointer=checkpointer)

    initial_state = {
        "inputs": spec["inputs"],
        "context": spec["context"],
        "step_1_output": "",
        "generated_output": "",
        "quality_score": 0.0,
        "critic_feedback": "",
        "retry_count": 0,
        "final_output": "",
        "artifact_path": "",
        "envelope_path": "",
        "error": "",
        "cost": 0.0,
    }

    config = {"configurable": {"thread_id": wf_id}}

    for step in app.stream(initial_state, config):
        for node_name, node_state in step.items():
            print(f"\n  [node] {node_name}")
            if node_state.get("error"):
                print(f"  [error] {node_state['error']}")
                break
            print(f"  [done] {node_name}")

    final = app.get_state(config)
    if final and final.values:
        vals = final.values
        if vals.get("artifact_path"):
            print(f"\nSkill complete: NDA Generator")
            print(f"Thread ID: {wf_id}")
            print(f"Output: {vals['artifact_path']}")
            print(f"Quality: {vals.get('quality_score', 0):.1f}/10")
            print(f"Cost: ${vals.get('cost', 0):.3f}")
        elif vals.get("error"):
            print(f"\nERROR: Skill failed — {vals['error']}")

    conn.close()
