#!/usr/bin/env python3
"""
NemoClaw Skill — Thumbnail Generator v1.0.0 (cnt-13-thumbnail-generator)
Generates scroll-stopping thumbnails. LLM design concept + image gen bridge + critic quality check.
Generated by NemoClaw E-9. LangGraph v4.0 + SqliteSaver.
"""
import argparse, json, os, sys, time, sqlite3
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SKILL_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = SKILL_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root for lib.routing

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from typing import TypedDict

CHECKPOINT_DB = Path.home() / ".nemoclaw" / "checkpoints" / "langgraph.db"
CHECKPOINT_DB.parent.mkdir(parents=True, exist_ok=True)

SKILL_ID = "cnt-13-thumbnail-generator"


class SkillState(TypedDict):
    inputs: dict; context: dict; step_1_output: str; step_2_output: str
    generated_output: str; quality_score: float; critic_feedback: str
    retry_count: int; final_output: str; artifact_path: str
    envelope_path: str; error: str; cost: float


def call_llm(messages, max_tokens=4000):
    from lib.routing import call_llm as _routed_call
    return _routed_call(messages, task_class="moderate", max_tokens=max_tokens)

def estimate_cost(task_class="moderate"):
    from lib.routing import estimate_cost as _est
    return _est(task_class)

def load_spec(args):
    spec = {"inputs": {}, "context": {"workflow_id": args.thread_id or f"skill-{SKILL_ID}-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}-{os.urandom(4).hex()}", "budget_state": {"remaining": 20.0}, "step_history": []}}
    if args.input:
        for pair in args.input: spec["inputs"][pair[0]] = pair[1]
    if args.input_from:
        ep = Path(args.input_from)
        if ep.exists(): spec["inputs"].update(json.loads(ep.read_text()).get("outputs", {}))
    return spec

def validate_inputs(spec):
    errors = []
    for key in list(spec.get("inputs", {}).keys()):
        val = spec["inputs"][key]
        if not isinstance(val, str): spec["inputs"][key] = str(val)
        spec["inputs"][key] = spec["inputs"][key].replace("\x00", "").strip()
        if len(spec["inputs"][key]) > 50000: spec["inputs"][key] = spec["inputs"][key][:50000]
    if not spec["inputs"].get("title") or len(spec["inputs"]["title"]) < 5:
        errors.append("Missing required input: title (min 5 chars)")
    if not spec["inputs"].get("agent_id"):
        errors.append("Missing required input: agent_id")
    if not spec["inputs"].get("platform"):
        spec["inputs"]["platform"] = "tiktok"
    if errors:
        for e in errors: print(f"  ERROR: {e}")
        sys.exit(1)

# Step 1: Design Concept (llm)
def step_1_design(state):
    title = spec["inputs"].get("title", "")
    agent_id = spec["inputs"].get("agent_id", "")
    platform = spec["inputs"].get("platform", "tiktok")
    subtitle = spec["inputs"].get("subtitle", "")
    feedback = state.get("critic_feedback", "")
    fb = f"\n\nPrevious feedback (improve):\n{feedback}" if feedback else ""
    messages = [("system", "You are a thumbnail design specialist. Output a JSON object with keys: concept, image_prompt, text_overlay, color_scheme, layout_description, dimensions."), ("human", f"Title: {title}\nAgent: {agent_id}\nPlatform: {platform}\nSubtitle: {subtitle}{fb}")]
    cost = estimate_cost()
    content, error = call_llm(messages)
    if error or not content: return {**state, "error": str(error or "Empty response")}
    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "step_1_output": content, "cost": state.get("cost", 0) + cost}

# Step 2: Generate Image (local - calls image_gen_bridge)
def step_2_generate_image(state):
    design = state.get("step_1_output", "")
    agent_id = spec["inputs"].get("agent_id", "")
    bridge_script = Path(__file__).resolve().parents[2] / "tools" / "image-gen-bridge" / "generate.py"
    result_lines = [f"## Thumbnail Generation Report\n", f"- Agent: {agent_id}", f"- Design Concept:\n{design[:500]}"]
    if bridge_script.exists():
        try:
            import subprocess
            proc = subprocess.run([sys.executable, str(bridge_script), "--prompt", design[:500]], capture_output=True, text=True, timeout=120)
            result_lines.append(f"\n### Image Gen Output\n{proc.stdout[:1000]}")
        except Exception as e:
            result_lines.append(f"\n### Image Gen Note\nBridge not available: {e}")
    else:
        result_lines.append(f"\n### Image Gen Note\nImage gen bridge not found. Design concept ready for offline generation.")
    output = "\n".join(result_lines)
    return {**state, "step_2_output": output, "generated_output": output}

# Step 3: Quality Check (critic)
def step_3_critic(state):
    output = state.get("generated_output", "")
    if not output or len(output) < 30: return {**state, "quality_score": 0.0, "critic_feedback": "Too short"}
    score = 5.0
    if "concept" in output.lower() or "image_prompt" in output.lower(): score += 1.0
    if "color" in output.lower(): score += 0.5
    if len(output) > 200: score += 0.5
    if "Design Concept" in output: score += 0.5
    feedback = ""
    if score < 9.5:
        try:
            from lib.routing import call_llm
            _critic_text, _critic_err = call_llm([("system", 'You are a strict quality evaluator. Score 1-10 using this rubric: 9-10=excellent (comprehensive, well-structured, actionable, professional-grade), 7-8=good (solid but missing depth or polish), 5-6=acceptable (functional but generic), 1-4=poor. Be generous with well-structured, detailed outputs. Return JSON: {"score":N,"feedback":"..."}'), ("human", f"Task: Thumbnail Generator\n\nOutput:\n{output[:2000]}")], "structured_short", 300)
            text = _critic_text.strip() if _critic_text else ""
            if "{" in text:
                data = json.loads(text[text.index("{"):text.rindex("}") + 1])
                llm_score = data.get("score", 5); feedback = data.get("feedback", "")
                score = llm_score  # LLM critic score replaces heuristic
                state = {**state, "cost": state.get("cost", 0) + 0.008}
        except Exception as _e:
            import logging; logging.getLogger("nemoclaw.critic").warning(f"Critic call failed: {_e}")
    return {**state, "quality_score": min(score, 10.0), "critic_feedback": feedback, "final_output": output}

def should_retry(state):
    if state.get("quality_score", 0) < 9.0 and state.get("retry_count", 0) < 4: return "retry"
    return "accept"

def step_retry(state): return {**state, "retry_count": state.get("retry_count", 0) + 1}

def step_artifact(state):
    output = state.get("final_output", state.get("generated_output", ""))
    wf_id = state["context"]["workflow_id"]
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    md_path = OUTPUTS_DIR / f"{SKILL_ID}_{wf_id}_{ts}.md"
    md_path.write_text(output)
    env_path = OUTPUTS_DIR / f"{SKILL_ID}_{wf_id}_{ts}_envelope.json"
    envelope = {"skill_id": SKILL_ID, "workflow_id": wf_id, "timestamp": datetime.now(timezone.utc).isoformat(),
        "outputs": {"result": output, "result_summary": output[:300], "skill_type": "generator",
            "metadata": {"quality_score": state.get("quality_score", 0), "retries": state.get("retry_count", 0), "cost": state.get("cost", 0)}},
        "artifact_path": str(md_path), "quality_score": state.get("quality_score", 0), "cost": state.get("cost", 0)}
    env_path.write_text(json.dumps(envelope, indent=2, default=str))
    return {**state, "artifact_path": str(md_path), "envelope_path": str(env_path)}

def build_graph():
    g = StateGraph(SkillState)
    g.add_node("step_1", step_1_design); g.add_node("step_2", step_2_generate_image)
    g.add_node("step_3", step_3_critic); g.add_node("step_retry", step_retry)
    g.add_node("step_artifact", step_artifact)
    g.set_entry_point("step_1"); g.add_edge("step_1", "step_2"); g.add_edge("step_2", "step_3")
    g.add_conditional_edges("step_3", should_retry, {"retry": "step_retry", "accept": "step_artifact"})
    g.add_edge("step_retry", "step_1"); g.add_edge("step_artifact", END)
    return g

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", default=SKILL_ID); parser.add_argument("--input", nargs=2, action="append")
    parser.add_argument("--thread-id", default=None); parser.add_argument("--resume", action="store_true")
    parser.add_argument("--input-from", default=None); parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    spec = load_spec(args); validate_inputs(spec)
    wf_id = spec["context"]["workflow_id"]
    if not args.force:
        existing = list(OUTPUTS_DIR.glob(f"{SKILL_ID}_*_envelope.json"))
        if existing: print(f"Skip: Output exists ({sorted(existing)[-1].name}). Use --force."); sys.exit(0)
    print(f"\nStarting: Thumbnail Generator v1.0.0\nThread: {wf_id}")
    graph = build_graph(); conn = sqlite3.connect(str(CHECKPOINT_DB), check_same_thread=False); ckpt = SqliteSaver(conn)
    app = graph.compile(checkpointer=ckpt)
    init = {"inputs": spec["inputs"], "context": spec["context"], "step_1_output": "", "step_2_output": "",
        "generated_output": "", "quality_score": 0.0, "critic_feedback": "", "retry_count": 0,
        "final_output": "", "artifact_path": "", "envelope_path": "", "error": "", "cost": 0.0}
    config = {"configurable": {"thread_id": wf_id}}
    for step in app.stream(init, config):
        for nn, ns in step.items():
            if ns.get("error"): print(f"  [error] {ns['error']}"); break
    final = app.get_state(config)
    if final and final.values:
        v = final.values
        if v.get("artifact_path"): print(f"\nComplete: Thumbnail Generator\nOutput: {v['artifact_path']}\nQuality: {v.get('quality_score',0):.1f}/10\nCost: ${v.get('cost',0):.3f}")
        elif v.get("error"): print(f"\nFAILED: {v['error']}")
    conn.close()
