#!/usr/bin/env python3
"""
NemoClaw Skill — Agent Self-Promotion Generator v1.0.0 (cnt-11-agent-self-promo-generator)
Generates weekly self-promotion briefs for each agent with FRIENDS-themed narrative style.
Generated by NemoClaw E-9. LangGraph v4.0 + SqliteSaver.
"""
import argparse, json, os, sys, time, sqlite3
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SKILL_DIR = Path(__file__).resolve().parent
OUTPUTS_DIR = SKILL_DIR / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root for lib.routing

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from typing import TypedDict

CHECKPOINT_DB = Path.home() / ".nemoclaw" / "checkpoints" / "langgraph.db"
CHECKPOINT_DB.parent.mkdir(parents=True, exist_ok=True)

SKILL_ID = "cnt-11-agent-self-promo-generator"


class SkillState(TypedDict):
    inputs: dict; context: dict; step_1_output: str; generated_output: str
    quality_score: float; critic_feedback: str; retry_count: int; final_output: str
    artifact_path: str; envelope_path: str; error: str; cost: float


def call_llm(messages, max_tokens=4000):
    from lib.routing import call_llm_or_chain
    return call_llm_or_chain(messages, task_class="moderate", task_domain="content", max_tokens=max_tokens)

def estimate_cost(task_class="moderate"):
    from lib.routing import estimate_cost as _est
    return _est(task_class)

def load_spec(args):
    spec = {"inputs": {}, "context": {"workflow_id": args.thread_id or f"skill-{SKILL_ID}-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}-{os.urandom(4).hex()}", "budget_state": {"remaining": 20.0}, "step_history": []}}
    if args.input:
        for pair in args.input: spec["inputs"][pair[0]] = pair[1]
    if args.input_from:
        ep = Path(args.input_from)
        if ep.exists(): spec["inputs"].update(json.loads(ep.read_text()).get("outputs", {}))
    return spec

def validate_inputs(spec):
    errors = []
    for key in list(spec.get("inputs", {}).keys()):
        val = spec["inputs"][key]
        if not isinstance(val, str):
            spec["inputs"][key] = str(val)
        spec["inputs"][key] = spec["inputs"][key].replace("\x00", "").strip()
        if len(spec["inputs"][key]) > 50000:
            spec["inputs"][key] = spec["inputs"][key][:50000]
    if not spec["inputs"].get("agent_id"):
        errors.append("Missing required input: agent_id")
    if not spec["inputs"].get("performance_data"):
        errors.append("Missing required input: performance_data")
    if errors:
        for e in errors: print(f"  ERROR: {e}")
        sys.exit(1)


def step_1_parse(state):
    """Parse performance_data JSON, extract wins/metrics/milestones."""
    raw = spec["inputs"].get("performance_data", "{}")
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        data = {"raw": raw}
    agent_id = spec["inputs"].get("agent_id", "unknown")
    name = data.get("name", agent_id)
    character = data.get("character", "")
    wins = data.get("wins", [])
    metrics = data.get("metrics", {})
    milestones = data.get("milestones", [])
    context = f"""Agent: {name} ({agent_id})
Character inspiration: {character}
Recent wins: {json.dumps(wins)}
Key metrics: {json.dumps(metrics)}
Milestones: {json.dumps(milestones)}"""
    return {**state, "step_1_output": context}


def step_2_generate(state):
    """Generate a FRIENDS-themed self-promotion brief."""
    context = state["step_1_output"]
    feedback = state.get("critic_feedback", "")
    fb = f"\n\nPrevious reviewer feedback (please improve):\n{feedback}" if feedback else ""
    messages = [
        ("system", """You are a creative social media strategist writing agent self-promotion briefs in the style of a FRIENDS TV show episode recap. Each brief should include:

1. **Episode Title** — A catchy FRIENDS-style episode title (e.g., "The One Where Hassan Closed Three Deals")
2. **Cold Open** — A punchy 2-sentence hook that grabs attention
3. **Talking Points** (3-5 bullets) — Key achievements framed as character moments
4. **Suggested Social Hooks** (3 options) — Short-form captions for Instagram/TikTok/LinkedIn
5. **Visual Ideas** (2-3) — Scene descriptions for graphics or short video concepts
6. **Hashtag Set** — 5-8 relevant hashtags

Keep the tone fun, confident, and professional. Make the agent sound like a beloved character having their best week."""),
        ("human", f"{context}{fb}")
    ]
    from lib.routing import resolve_from_env_or_config as _resolve
    provider, model, _cost = _resolve("moderate")
    cost = estimate_cost()
    content, error = call_llm(messages)
    if error or not content:
        return {**state, "error": str(error or "Empty response")}
    state["context"]["budget_state"]["remaining"] -= cost
    return {**state, "generated_output": content, "cost": state.get("cost", 0) + cost}


def step_3_critic(state):
    """Score the brief quality 1-10."""
    output = state.get("generated_output", "")
    if not output or len(output) < 50:
        return {**state, "quality_score": 0.0, "critic_feedback": "Too short"}
    score = 5.0
    if len(output) > 200: score += 0.5
    if len(output) > 500: score += 0.5
    if "##" in output or "**" in output: score += 0.5
    if "- " in output or "1." in output: score += 0.5
    if "hook" in output.lower() or "visual" in output.lower(): score += 0.5
    feedback = ""
    if score < 10.5:
        try:
            from lib.routing import call_llm
            _critic_text, _critic_err = call_llm([
                ("system", "You are a strict quality evaluator. Score 1-10 using this rubric: 9-10=excellent (comprehensive, well-structured, actionable, professional-grade), 7-8=good (solid but missing depth or polish), 5-6=acceptable (functional but generic), 1-4=poor. Be generous with well-structured, detailed outputs. Return JSON: {\"score\":N,\"feedback\":\"...\"}"),
                ("human", f"Task: Agent Self-Promotion Brief\n\nOutput:\n{output[:2000]}")
            ], "structured_short", 300)
            text = _critic_text.strip() if _critic_text else ""
            if "{" in text:
                data = json.loads(text[text.index("{"):text.rindex("}") + 1])
                llm_score = data.get("score", 5)
                feedback = data.get("feedback", "")
                score = llm_score  # LLM critic score replaces heuristic
                state = {**state, "cost": state.get("cost", 0) + 0.008}
        except Exception:
            pass
    return {**state, "quality_score": min(score, 10.0), "critic_feedback": feedback, "final_output": output}


def should_retry(state):
    if state.get("quality_score", 0) < 10.0 and state.get("retry_count", 0) < 5:
        return "retry"
    return "accept"

def step_retry(state):
    return {**state, "retry_count": state.get("retry_count", 0) + 1}


def step_5_artifact(state):
    """Write final brief to output file and envelope."""
    output = state.get("final_output", state.get("generated_output", ""))
    wf_id = state["context"]["workflow_id"]
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    md_path = OUTPUTS_DIR / f"{SKILL_ID}_{wf_id}_{ts}.md"
    md_path.write_text(output)
    key_points = [l.lstrip("- *0123456789.").strip() for l in output.split("\n") if l.strip().startswith(("- ", "1.", "* "))][:10]
    env_path = OUTPUTS_DIR / f"{SKILL_ID}_{wf_id}_{ts}_envelope.json"
    envelope = {
        "skill_id": SKILL_ID, "workflow_id": wf_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "outputs": {
            "result": output, "result_summary": output[:300],
            "key_points": key_points, "skill_type": "generator",
            "metadata": {
                "quality_score": state.get("quality_score", 0),
                "retries": state.get("retry_count", 0),
                "cost": state.get("cost", 0),
                "model": __import__("lib.routing", fromlist=["resolve_from_env_or_config"]).resolve_from_env_or_config("moderate")[1]
            }
        },
        "artifact_path": str(md_path),
        "quality_score": state.get("quality_score", 0),
        "cost": state.get("cost", 0)
    }
    env_path.write_text(json.dumps(envelope, indent=2, default=str))
    return {**state, "artifact_path": str(md_path), "envelope_path": str(env_path)}


def build_graph():
    g = StateGraph(SkillState)
    g.add_node("step_1", step_1_parse)
    g.add_node("step_2", step_2_generate)
    g.add_node("step_3", step_3_critic)
    g.add_node("step_retry", step_retry)
    g.add_node("step_5", step_5_artifact)
    g.set_entry_point("step_1")
    g.add_edge("step_1", "step_2")
    g.add_edge("step_2", "step_3")
    g.add_conditional_edges("step_3", should_retry, {"retry": "step_retry", "accept": "step_5"})
    g.add_edge("step_retry", "step_2")
    g.add_edge("step_5", END)
    return g


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", default=SKILL_ID)
    parser.add_argument("--input", nargs=2, action="append")
    parser.add_argument("--thread-id", default=None)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--input-from", default=None)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    spec = load_spec(args)
    validate_inputs(spec)
    wf_id = spec["context"]["workflow_id"]
    if not args.force:
        existing = list(OUTPUTS_DIR.glob(f"{SKILL_ID}_*_envelope.json"))
        if existing:
            print(f"Skip: Output exists ({sorted(existing)[-1].name}). Use --force.")
            sys.exit(0)
    print(f"\nStarting: Agent Self-Promotion Generator v1.0.0\nThread: {wf_id}")
    graph = build_graph()
    conn = sqlite3.connect(str(CHECKPOINT_DB), check_same_thread=False)
    ckpt = SqliteSaver(conn)
    app = graph.compile(checkpointer=ckpt)
    init = {
        "inputs": spec["inputs"], "context": spec["context"],
        "step_1_output": "", "generated_output": "",
        "quality_score": 0.0, "critic_feedback": "", "retry_count": 0,
        "final_output": "", "artifact_path": "", "envelope_path": "",
        "error": "", "cost": 0.0
    }
    config = {"configurable": {"thread_id": wf_id}}
    for step in app.stream(init, config):
        for nn, ns in step.items():
            if ns.get("error"):
                print(f"  [error] {ns['error']}")
                break
    final = app.get_state(config)
    if final and final.values:
        v = final.values
        if v.get("artifact_path"):
            print(f"\nComplete: Agent Self-Promotion Generator\nOutput: {v['artifact_path']}\nQuality: {v.get('quality_score',0):.1f}/10\nCost: ${v.get('cost',0):.3f}")
        elif v.get("error"):
            print(f"\nFAILED: {v['error']}")
    conn.close()
