#!/usr/bin/env python3
"""
NemoClaw Skill: research-brief
Step execution logic. Phase 6: Direct API calls — no OpenShell dependency.
Called by skill-runner.py for each step.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone


# ── LLM Helpers (routed through lib/routing.py — L-003 compliant) ────────────
def call_openai(messages, model=None, max_tokens=1500):
    from lib.routing import call_llm
    return call_llm(messages, task_class="general_short", max_tokens=max_tokens)

def call_anthropic(messages, model=None, max_tokens=1500):
    from lib.routing import call_llm
    return call_llm(messages, task_class="complex_reasoning", max_tokens=max_tokens)

def call_google(messages, model=None, max_tokens=1500):
    from lib.routing import call_llm
    return call_llm(messages, task_class="moderate", max_tokens=max_tokens)


def step_1_validate_and_plan(inputs, context):
    """Validate topic and create research plan."""
    topic = inputs.get("topic", "").strip()
    depth = inputs.get("depth", "standard")

    if not topic or len(topic) < 5:
        return None, "Topic too short or empty"

    depth_map = {
        "brief":    "Cover the main points only. 3-4 key findings.",
        "standard": "Provide a thorough overview. 5-7 key findings.",
        "deep":     "Provide comprehensive coverage. 8+ key findings with supporting detail.",
    }
    depth_instruction = depth_map.get(depth, depth_map["standard"])

    plan = f"""Research Topic: {topic}
Depth: {depth}
Instructions: {depth_instruction}

Research Plan:
1. Background — what is this topic and why does it matter
2. Key Findings — most important facts, data, and insights
3. Open Questions — what remains unresolved or debated
4. Recommendations — actionable next steps or conclusions

Please conduct thorough research on this topic following the plan above."""

    return {"output": plan}, None


def step_2_research_topic(inputs, context):
    """Deep research using reasoning model via direct Anthropic API."""
    plan = context.get("research_plan", "")
    if not plan:
        return None, "No research plan found in context"

    messages = [
        {"role": "system", "content": "You are a rigorous research analyst. Produce structured, factual research briefs with clear sections for Background, Key Findings, Open Questions, and Recommendations."},
        {"role": "user", "content": f"""{plan}

Produce a detailed research response covering all four sections: Background, Key Findings, Open Questions, and Recommendations.
Be specific and direct. Use concrete facts where possible. Be clear about what is known vs uncertain.
Format each section with a clear markdown header."""}
    ]

    # Use model resolved by routing system — respect budget enforcer decisions including fallbacks
    resolved_model = context.get("resolved_model", "")
    resolved_provider = context.get("resolved_provider", __import__("lib.routing", fromlist=["resolve_alias"]).resolve_alias("moderate")[0])

    if resolved_provider == "google":
        content, error = call_google(messages, model=resolved_model, max_tokens=6000)
    elif resolved_provider == "openai" or resolved_provider not in ("anthropic", "google"):
        content, error = call_openai(messages, model=resolved_model, max_tokens=6000)
    else:
        content, error = call_anthropic(messages, model=resolved_model, max_tokens=6000)

    if error:
        # Fallback to OpenAI if primary provider fails
        content, error = call_openai(messages, max_tokens=6000)
    if error:
        return None, error

    return {"output": content}, None


def step_3_structure_findings(inputs, context):
    """Structure raw research into clean brief format."""
    raw = context.get("raw_research", "")
    if not raw:
        return None, "No raw research found in context"

    topic_from_plan = ""
    plan = context.get("research_plan", "")
    for line in plan.split(chr(10)):
        if line.startswith("Research Topic:"):
            topic_from_plan = line.replace("Research Topic:", "").strip()
            break

    brief = f"""# Research Brief: {topic_from_plan}

**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}
**Depth:** {inputs.get('depth', 'standard')}

---

{raw}

---

*This brief was generated by the NemoClaw research-brief skill v1.0.0*"""

    return {"output": brief}, None


def step_4_validate_output(inputs, context):
    """Critic step: evaluate quality of the structured brief."""
    brief = context.get("structured_brief", "")
    if not brief:
        return None, "No structured brief found in context"

    # Deterministic checks
    required_sections = ["Background", "Key Findings", "Open Questions", "Recommendations"]
    missing = [s for s in required_sections if s not in brief]
    score = 5.0
    if not missing: score += 1.0
    if len(brief) > 200: score += 0.5
    if len(brief) > 500: score += 0.5
    if "##" in brief: score += 0.5
    if "- " in brief or "1." in brief: score += 0.5

    feedback = ""
    if score < 10.5:
        try:
            from lib.routing import call_llm as _routed_call
            _critic_text, _critic_err = _routed_call(
                [("system", "You are a strict quality evaluator. Score 1-10: 9-10=excellent, 7-8=good, 5-6=acceptable, 1-4=poor. Be generous with well-structured outputs. Return JSON: {\"score\":N,\"feedback\":\"...\"}"),
                 ("human", f"Task: Research Brief\n\nOutput:\n{brief[:2000]}")],
                "structured_short", 300)
            text = _critic_text.strip() if _critic_text else ""
            if "{" in text:
                import json
                data = json.loads(text[text.index("{"):text.rindex("}")+2])
                score = data.get("score", 5)
                feedback = data.get("feedback", "")
        except Exception:
            pass

    return {"output": brief, "validated_brief": brief,
            "quality_score": min(score, 10.0), "feedback": feedback}, None


def step_4b_improve_brief(inputs, context):
    """Improve brief based on critic feedback."""
    brief = context.get("structured_brief", "")
    feedback = context.get("step_4_output", {})
    fb_text = feedback.get("feedback", "") if isinstance(feedback, dict) else ""
    if not fb_text:
        return {"output": brief}, None

    from lib.routing import call_llm as _routed_call
    messages = [
        ("system", "You are a research analyst. Improve the brief based on the feedback. Keep the same structure (Background, Key Findings, Open Questions, Recommendations)."),
        ("human", f"Brief:\n{brief}\n\nFeedback to address:\n{fb_text}\n\nImproved brief:")
    ]
    content, error = _routed_call(messages, "complex_reasoning", 4000)
    if error or not content:
        return {"output": brief}, None
    return {"output": content, "structured_brief": content}, None


def step_5_write_artifact(inputs, context):
    """Artifact writing is handled by skill-runner.py directly."""
    return {"output": "artifact_written"}, None


STEP_HANDLERS = {
    "step_1": step_1_validate_and_plan,
    "step_2": step_2_research_topic,
    "step_3": step_3_structure_findings,
    "step_4": step_4_validate_output,
    "step_4b": step_4b_improve_brief,
    "step_5": step_5_write_artifact,
}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--step", required=True)
    parser.add_argument("--input", required=True)
    args = parser.parse_args()

    with open(args.input) as f:
        spec = json.load(f)

    step_id = spec["step_id"]
    inputs  = spec["inputs"]
    context = spec["context"]

    handler = STEP_HANDLERS.get(step_id)
    if not handler:
        print(json.dumps({"error": f"Unknown step: {step_id}"}))
        sys.exit(1)

    result, error = handler(inputs, context)
    if error:
        print(json.dumps({"error": error}))
        sys.exit(1)

    print(json.dumps(result))
